### ISSUE TITLE
Add function to load terms from database.

### ISSUE THREAD

**Issue by LukasS96** [MusicConnectionMachine/UnstructuredData#103]
We need a function to load the entities group 1 provides from the database. 
This should be implemented in term-loader.ts

Also, we need to refactor our code: Right now, a term is a string. We need to make term an object with the attributes name and databaseId. This is required to create the relationship in the database when storing the webpage later on. 
This means that all current usages of term have to be refactored so that they now refer to the name of the term.

**Comment by lgfrbcsgo** [comment]
> This means that all current usages of term have to be refactored so that they now refer to the name of the term.

That's a lot. All `Filter` classes have to be changed and the `Occurrence` class

**Comment by nyxathid** [comment]
Not yet, I'll start a bit later ;)

**Comment by lgfrbcsgo** [comment]
Ok then, then only tricky part should be the occurrence merging function in `WebPage` and the conversion functions in `Occurrence`.

**Comment by nyxathid** [comment]
Guys, the idea with storing term+ID together in an object was good in theory but fails **miserably** in reality. 

I tried to implement it but it would completely break the filters when it comes to performance. For all filters, we have to store a Map (term -> id). otherwise we just can return the found string (no ID). And there is more: for every match we have to look up the ID.

Tons of work are needed to rewrite many tests.

Additionally, with this approach we can forget about using Sets (and we rely on them a lot!). Why? Because `new Term("1", "1") == new Term("1", "1")` is `false`! There is no way to override `==` and there is also no `equals`. Well, JavaScript, you suck. Custom Sets for Terms are an overkill.

I'm going to throw away all my today's code. The refactoring is possible but would have a significant performance overhead in the very critical filtering part. It's much cheaper and easier to look up the term ID every time we write to the DB.

Lessons learned: 
- keep it (filters) simple and stupid, otherwise refatoring will be expensive
- there is no `equals` in JS, forget about complex objects inside sets

BTW, at least one test is broken:
`should merge occurrences`  in `webpage-digester-test.ts`
`assert(result, expected)` is `undefined`

**Comment by nyxathid** [comment]
Term refactoring is mostly done. Filter functionality remains the same `WebPageDigester` does the necessary wrapping.  We can now concentrate on DB access.

**Comment by nyxathid** [comment]
First steps with DB were done here: https://github.com/MusicConnectionMachine/UnstructuredData/pull/113
This PR also contains a short description how to get a local DB running

**Comment by lgfrbcsgo** [comment]
Can this be closed? @nyxathid 
Loading terms form the DB seems to be working, right?

**Comment by nyxathid** [comment]
No, input from DB is not complete. So far we only read artist names.
We should read more: instruments, genres, recordings etc.

**Comment by lgfrbcsgo** [comment]
Ah ok, I see
