### ISSUE TITLE
Quality of the generated data

### ISSUE THREAD

**Issue by kordianbruck** [MusicConnectionMachine/UnstructuredData#145]
1. So how does the quality of the data look right now? 
2. Does it need improvement?
3. How can we do it?
4. Is the ranking working? 
5. Other thoughts?

**Comment by lgfrbcsgo** [comment]
1. It outputs every page with at least one match. Matches might be false positives `Sturzbach`, `Bachlauf` would be matches for `Bach`.
2. Yes
3. A simple rule that a page should at least contain `x` occurrences would improve it by a lot
4. There is no ranking, as it was deemed not useful
5. Nope

**Comment by sacdallago** [comment]
So basically this few days, on feature freeze, some of the cleanup items like 1., 2. (and 3. which is OTW) can be implemented or partially so, right? :) I mean, in the spirit of cleaning up slightly, it's not really adding features. But: integration comes first! :)

**Comment by vviro** [comment]
@lgfrbcsgo Regarding Sturzbach and Bachlauf, if matching just Bach is an issue, could one just search for " Bach " with spaces before and after? Won't that be a quick fix? Regarding the third item, definitely, please do this! Better filter too much than too little, especially since the computation resources for relation extraction probably won't be sufficient for processing the false positives, and even weak true positives. We'd be lucky to be able to process pages that are relevant beyond doubt. So, what would your heuristic be? Which thresholds are you thinking of using?

**Comment by lgfrbcsgo** [comment]
> Regarding Sturzbach and Bachlauf, if matching just Bach is an issue, could one just search for " Bach " with spaces before and after? Won't that be a quick fix?

@vviro That's pretty much the intended fix. The only problem is that there could be a comma, exclamation mark, etc directly after a term. Accounting for all the possible punctuation would blow up our search terms pretty quickly. I'll test something very similar with the `PreefixTree`.

> So, what would your heuristic be? Which thresholds are you thinking of using?

Probably a mix between the number of different term occurrences and the number of times a single term occurs in a page. So if `Bach` is contained in an article 5 times that not as good as if `Bach` and `Mozart` are contained in an article. I am trying to come up with a heuristic which reflects that.

**Comment by lgfrbcsgo** [comment]
Discussion moved to #149. Can be closed now.
