### ISSUE TITLE
Running this on azure

### ISSUE THREAD

**Issue by lukasstreit** [MusicConnectionMachine/UnstructuredData#149]
We need to create azure instances to run this on and start the script execution on them.

Our first approach was to create a virtual machine scale set on azure which seemed fitting for this use case. It allows us to quickly add or remove instances but also comes with some difficulties: We didn't figure out how to actually deploy our docker container to this and we also didn't manage to get ssh access to the vms. The deployment script for this seems rather complicated and might take some time to understand.

The alternative would be to manually spawn single vm instances contained in a resource group. This way, we could have a more direct access and would have to deploy to each instance one at a time. This might be faster for the initial run but would probably bring some overhead in the long run.

**Comment by lgfrbcsgo** [comment]
Do we have to run this more than once? I think @sacdallago said during one of the hackathlons that we should start the app via the command line. So I'd say do the latter over SSH.

**Comment by sacdallago** [comment]
Well, we probably will run the scrapers once every couple months, right? So I like the idea of creating a resource group with all necessary machines, services, and what not, and then undeploy everything when it's not being used. Finally, whenever the data needs to be re-scraped, bring everything up again and scrape :)

Yes / No ?

**Comment by lgfrbcsgo** [comment]
We would need some centralized instance who keeps track of which VMs have to process which WET files. @sacdallago

**Comment by lgfrbcsgo** [comment]
We should probably start small with a single VM and do some performance testing with the amount of processes to spawn and gain results for the first few WET files that way.

**Comment by sacdallago** [comment]
Good. Sounds to me like this is something you should try out before Saturday and then you tell me specifics on the hackathon @LukasS96 . Btw this is related to the ongoing discussion [here](https://github.com/MusicConnectionMachine/UnstructuredData/issues/136#issuecomment-295274697)

**Comment by vviro** [comment]
**high priority**

@vviro and @goldbergtatyana from vviro's office:

*do not* wait till Saturday @lgfrbcsgo, for the run, also we don't need performance testing now. Just launch the computations as soon as you can. As per our discussion on Gitter, let's start with 20 VMs and check two hours later how much data has been processed.

@lgfrbcsgo please report to us here when you started the processes and/or faced any errors that might will appear.

**Comment by vviro** [comment]
@sacdallago Is it possible to monitor the running costs of this processing step (e.g. the above 20 VMs)?

**Comment by LukasS96** [comment]
## Numbers so far
### Configuration
_cores:_ 8
_processes:_ 8
_wet files:_ 16 (16-31)
_heuristic strictness:_ 4
_crawlset:_ CC-MAIN-2017-13

### Results
**Test run with pre-filters:**
_time:_ ~11 min
_results:_ 11284

**without pre-filters:**
_time:_ ~9:30
_results:_ 11210

### Conclusion
Processing is decently fast, could have been worse. 
The results so far contain a lot of junk, which is why we should increase heuristic strictness.
Also, many bogus matches were due to terms like "Deo" or "Oud". I suggest we filter out terms with less than 4 characters, even if that means losing out on some information. Terms with less than 4 characters are very rare in the database but result in a large amount of nonsensical results.

8 Processes for 8 threads seemed to nicely make use of the available processing power since CPU usage was very close to 100% almost all of the time.

The cost of these test runs is unknown so far but @sacdallago will hopefully be able to tell tomorrow. 
Until then it's probably best to not launch any more of them.

**Comment by LukasS96** [comment]
We have some especially weird matches that we can't backtrace, such as almost 50% of the first test runs terms having "Lute concerts from the 18th century" as a match. @lgfrbcsgo is currently working on that.

**Comment by lgfrbcsgo** [comment]
**OK, everything on halt. There is a but in `PrefixTree`!**

**Comment by lgfrbcsgo** [comment]
> Also, many bogus matches were due to terms like "Deo" or "Oud".

That's caused by not checking for word beginnings and endings. Will implement that tomorrow.

**Comment by sacdallago** [comment]
:D See this is a good reason why not waiting for the hackathon is good :) Keep the good work up @LukasS96  and @lgfrbcsgo , you might not get our :ninja: references, but for the rest you are alright
![](http://clipart-library.com/image_gallery/6735.gif)

**Comment by lgfrbcsgo** [comment]
Implementing #167 had huge impact!

> IT WERKS! It reduces the mount of database entries by 6-7 times!

> the most frequent term is now guitar instead of deo.

**Comment by LukasS96** [comment]
## Even more numbers
We did some more test runs with the changes done by @lgfrbcsgo.
Both test runs use the new heuristic as implemented in #166.
First run was with the prefix tree fix, see #163 
Second run was with the new prefix checking which makes sure that terms such as "deo" don't match on "video", etc., see #167 

Times were tested with the "time [command]" command.

This time we also checked the "top 10" most occuring terms. Ratio in number of occurences from nr 1 to number 10 is a decent indicator for how much junk our data probably contains. A higher ratio is an indicator for bad data quality. This is because if there is one term with an especially high amount of matches, it is likely that this term matches something that it shouldn't match. Best example for this is "deo".

### Configuration
_cores:_ 8
_processes:_ 8
_wet files:_ 16 (0-15)
_heuristic strictness:_ 4
_crawlset:_ CC-MAIN-2017-13

### Results
**Test run with fix in #163**
_time:_ 00:09:45
_results:_ 8600
_nr1 occurences:_ 7177
_nr10 occurences:_ 1645

**Test run with prefix checking #167**
_time:_ 00:09:36
_results:_ 1680
_nr1 occurences:_ 1087
_nr10 occurences:_ 565

### Conclusion
The prefix checking greatly reduced the total amount of matches, which is **GREAT**. We can be sure that we mostly lost junk websites and our data quality seems to have improved at the cost of no additional processing effort!

**Comment by vviro** [comment]
@sacdallago We need to be able to start large-scale processing **ASAP**. In order to do this, we need to know that the $ caps are off now and we won't get Azure frozen again. Please add all the funds to the pool and let us know here. Thanks!

**Comment by sacdallago** [comment]
[This doesn't surprise me](https://github.com/MusicConnectionMachine/UnstructuredData/issues/149#issuecomment-295914309) :) and I'm happy it happened.

@LukasS96 @lgfrbcsgo @vviro you can try large scale, ping me from time to time to check the balance, directly via private chat on gitter

**Comment by lgfrbcsgo** [comment]
@sacdallago Our deployment shell script for creating 100 VMs fails after around 30 machines and I have no clue why... @LukasS96 stayed up until 5am this morning and was trying to get it running... 

I certainly can't fix that on my own, as I am lacking the experience to do so... Seriously, all I can do right now is wait for @LukasS96 to come back from work...

![](http://s2.quickmeme.com/img/d1/d1740c7c7b38d898327c02165d028be97edb24519b268091034940c6949575c4.jpg)

**Comment by sacdallago** [comment]
@lgfrbcsgo show the script!

@pfent is a bash **expert**. He thinks in bash

**Comment by lgfrbcsgo** [comment]
That's what we've (actually only @LukasS96) have produced this night... 
https://files.gitter.im/MusicConnectionMachine/UnstructuredData/DX7x/deployment.zip

In theory it should just clone an already setup machine a 100 times...

**Comment by sacdallago** [comment]
![screen shot 2017-04-21 at 11 40 54](https://cloud.githubusercontent.com/assets/6240943/25272239/6dcc8d2e-2687-11e7-9b81-d99102ca6f9b.png)
seriously? 🗡

**Comment by lgfrbcsgo** [comment]
Ok, I think I know it... I probably shouldn't post it here though...

**Comment by pfent** [comment]
IMHO, just set up 20 machines per region and we'll be fine 🙈 

working on the bash scripts with @lgfrbcsgo

**Comment by lgfrbcsgo** [comment]
Thanks, @pfent. 

One question though. With the script we're creating 100 VMs spread over 5 locations. All the VMs should then be added to the same VNet. Can an Azure VNet span over multiple locations that easily or are we missing a step here? @sacdallago

**Comment by lgfrbcsgo** [comment]
Will this work?

https://gist.github.com/lgfrbcsgo/bd4a10a645de3cbefb2de9a0931e5b40

**Comment by pfent** [comment]
@lgfrbcsgo Nitpick: You can probably do the SSH password as an environment variable, that's usually the way to go for the *private parts*…

Anyways… you can probably commit those scripts to the repo, so we don't loose them and have version history.

**Comment by lgfrbcsgo** [comment]
> Anyways… you can probably commit those scripts to the repo, so we don't loose them and have version history.

#172

**Comment by lgfrbcsgo** [comment]
Well, we were starting 40ish VMs and then https://github.com/MusicConnectionMachine/api/issues/108 happened.

![](https://cdn-images-1.medium.com/max/800/1*NZaNH0SFe67HtTxKrPXkAg.png)

We've stopped all of the VMs for now and will be starting 8 different VMs for now to do some processing over night.

**Comment by lgfrbcsgo** [comment]
Ok, we've got 8 VMs with 8 processes each running now.

**Comment by felixschorer** [comment]
Can be closed now. Everything is running flawless. Should finish in a few hours 😄
