### ISSUE TITLE
Filter websites by top level domains to get mostly only english websites

### ISSUE THREAD

**Issue by LukasS96** [MusicConnectionMachine/UnstructuredData#16]
Domains should include but not necessarily be limited to: .com, .gb, .au, .uk, .us, .edu, .info, .museum, .net, .org

**Comment by kordianbruck** [comment]
I'd rather filter by the HTML Meta Tag: https://stackoverflow.com/questions/4417923/html-meta-tag-for-content-language

**Comment by lgfrbcsgo** [comment]
@kordianbruck Well, we've decided to go with ```.wet``` files instead of ```.wat``` files. Reason being that ```.wet``` files are a lot smaller and therefore easier to work with and also only contain already extracted content without HTML tags. Also HTML Meta Tags aren't mandatory and therefore aren't present on every website. Filtering by top level domain wouldn't be the only filter though. 
Thanks for the suggestion though, maybe we'll switch back to ```.wat``` if enough websites include that tag.

**Comment by kordianbruck** [comment]
I would primarily go by the meta tag and then have the domain. Domains today do not reflect at all, what language the content is in.

**Comment by lgfrbcsgo** [comment]
True, but the percentage of English sites with ```.de``` or ```.ru``` top level domain is rather small.

**Comment by lgfrbcsgo** [comment]
When filtering by top level domain and meta tag, I'd choose the top level domain as the first filter as it's less computational intense and reduces the data to a much smaller set.

**Comment by pfent** [comment]
@lgfrbcsgo Why not use a package that does real language detection, instead of inventing some heuristics? Looking at the first couple of words for each file shouldn't be too troublesome…

[franc](https://github.com/wooorm/franc) seems to do a decent job and you'll not just throw away half of the internet without ever looking at it

**Comment by lgfrbcsgo** [comment]
@pfent I was thinking about language detection as well, but dismissed it due to performance concerns without really looking into the matter. I think we'll test both pure language detection and filtering by top level domain first and then doing language detection.

**Comment by pfent** [comment]
I'd always test, if language detection is viable. If it's really too slow, you can always prune some unlikely TLDs, but please *based on your data* and not on some gut feeling 🎉

**Comment by sacdallago** [comment]
I totally agree with @pfent . Go with highest confidence solutions first and work down from there :)

**Comment by nyxathid** [comment]
Now we actually have some data about TLD and the language of the page. Run `testLanguageExtractor_slightly_better()` in `test-runs.ts`. For each entry you will get something like this:
`TLD: com 	IsEnglish: false`

Based on this data we can decide, if it is feasible or not to use TLD filtering. The `franc` package might be accurate but is definitely too slow to filter all the data.

**Comment by lgfrbcsgo** [comment]
Closed. Google's CLD package is really fast at detecting languages and uses TLDs as an hint for faster recognition. Implemented in 990161b by @LukasS96.
