### ISSUE TITLE
Progress indication

### ISSUE THREAD

**Issue by sacdallago** [MusicConnectionMachine/UnstructuredData#179]
Have means to check:
- [ ] status of the workers
- [ ] overall competition of processing the WAR files

Something in the fashion:

Worker1: /////////////////50%_____________
Worker2: //////////////////////70%_________
Worker3: /////////20%___________________
Worker4: ////////////////////////////90%____

Total: /////////////////50%_____________

**Comment by lgfrbcsgo** [comment]
How does console.log() work when randomly connecting via SSH?

**Comment by sacdallago** [comment]
You can pipe the output to a file on the remote machine (since you are running the scripts in background?), or even better on the caller machine ([random first hit on google](https://unix.stackexchange.com/questions/297438/capture-stdout-from-ssh-session-to-local-machine)).

On the master: you should know when an ssh connection is dropped --> process on remote completed --> x WET files have been parsed

**Comment by pfent** [comment]
You could also go the full loop and setup a small webserver (e.g. 7 LoC with [express](http://stackoverflow.com/a/4296402)), to which we [POST](https://stackoverflow.com/questions/6158933/how-to-make-an-http-post-request-in-node-js/12999483#12999483) the current progress 🤔

**Comment by vviro** [comment]
I would suggest you take a look at the queues, they would make the whole pipeline much less brittle and more efficient.
http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/sqs-examples-using-queues.html
http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/sqs-examples-send-receive-messages.html
https://docs.microsoft.com/en-us/azure/storage/storage-nodejs-how-to-use-queues

The code generating the tasks would be as complex as
`queueSvc.createMessage('taskQueue', "{work: description}", function(error, result, response){
  if(!error) {
    // Message is inserted
  }
});`

The code consuming the tasks from the queue would look like 
`queueSvc.getMessages('taskQueue', function(error, result, response){
  if(!error){
    // Message text is in messages[0].messageText
    var message = result[0];

    // process the message....

    // after the processing successfully finishes
    queueSvc.deleteMessage('taskQueue', message.messageId, message.popReceipt, function(error, response){
      // this code actually quite optional and not really necessary
      if(!error){
        //message deleted
      }
    });
  }
});`

And that's it. So, you just push all the tasks into the queue and see how the number of messages in the queue decreases while your slaves are processing the tasks (here you have your progress indicator). No explicit partitioning of tasks is required, no complexity, no processing same messages again, no caring for idle nodes (unless the code crashes, of course), and many additional benefits. All with the simple code above. Why not do this instead of building on top of the current brittle process?

**Comment by LukasS96** [comment]
I like @vviro's approach, my only worry is the additional debugging implementing a new solution would bring at this point.
We could use a webservice that starts the whole processing on a post request and returns information on the current progress on a get. Obviously some kind of authentication would be required here.

I don't really see how this would take care of sshing into the machines to deploy and start node quite yet, though. 

Auto-shutdown might be possible by sending a queue-item called 'shutdown' from the webservice to the machine which triggers the machine to run the shutdown command in shell.

**Comment by vviro** [comment]
@LukasS96 you cannot send a message to a particular machine over a queue, that's not how they are supposed to be used. Yes, auto-killing dead machines is something that needs to be taken care of by other means. But the point is, that barring the NodeJS process dying, there is no need to kill the machines because they will always have tasks unless everything is done, at which point we can kill all the machines.

**Comment by vviro** [comment]
there is also ne need to ssh into the machines because the node process can be started without any custom  parameters when the machine is initialized.

**Comment by vviro** [comment]
I know, I know, that's for brevity and for you catching this - well done :+1:

**Comment by lgfrbcsgo** [comment]
Queue implemented. Progress can be monitored by the amnout of items in the queue.
