### ISSUE TITLE
Filter WebPage objects by list of terms

### ISSUE THREAD

**Issue by nyxathid** [MusicConnectionMachine/UnstructuredData#37]
We will get a list of relevant terms from group 1. We should be able to filter WebPage objects created from entries of unpacked WET files based on these terms: If the entry doesn't contain any of the terms, it is skipped (or has a lower priority) in further processing.

**Comment by lgfrbcsgo** [comment]
There are 2 possible ways of doing that, that I know of:

- bool search: 1 vector per website where every index represents a word. v_i is either 1 when said word is present in the website or 0 if it isn't.

- tf-idf: basicially like boolen search but instead of 1 or 0 v_i is the tf*idf score for said word.

We have to save these vectors somehow. A simple search with regex won't cut it as it doesn't scale as well.

**Comment by nyxathid** [comment]
For IDF we need a set of documents. If we already use IDF during filtering we probably need to run TF-IDF on a large set of documents (before filtering). The first approach is easier. We can simply count how many terms (and how many occurences) are on the page -> simple integer as priority. I would then take top n pages and run TF-IDF on them later (after filtering or as next filtering step)

**Comment by nyxathid** [comment]
And of course a page with "Mozart is A; Mozart is B" should have a higher priority than "Mozart is C". More "Mozarts" -> more facts about him

**Comment by nyxathid** [comment]
Basic functionality implemented, optimizations are discussed in #59
