### ISSUE TITLE
Improve performance of language detection

### ISSUE THREAD

**Issue by lgfrbcsgo** [MusicConnectionMachine/UnstructuredData#49]
`cld` tells us when it couldn't detect a pages's language. The idea is that we feed `cld` only with a tiny fragment of a page and give it some more content if it fails to detect the language.

- Find the optimal size for the initial page fragment

- How big should successive fragments be in case it fails to detect the language?

- Does it actually yield any performance benefit?

**Comment by anshul0708** [comment]
In the current test data, CLD at chunk size 500 recognizes the language for 29653 pages and doesn't for 23858 pages. Too many pages are discarded now.
 
I checked other chunk sizes 300 and 1000 as well. Chunk size doesn't have any big impact on performance and detection accuracy. At all different chunk sizes the execution time and detection accuracy remained roughly constant.

Feeding a combination of the beginning, middle and end, may work better than varying chunk sizes.

**Comment by sacdallago** [comment]
@anshul0708 that is roughly 50% of the data being detected, and 50% not, on top of that of the 50% detected one how much is english? Or how much is any language? Just to understand the figures. Because if it ends up being that 2000 pages are scraped, that is not very impressive.

Also: have you thought of classifying domains by language? A logic of the type:
xyz.com --> classified 10 out of 50 pages, 5 out of 10 classified as english, the other 5 unknown or with high variance --> xyz.com is english

xyz.it --> classified 10 out of 50 pages, 5 out of 10 classified as italian, the other 5 english --> xyz.it is (a degree of english, not english?)

xyz.co --> classified 10 out of 50 pages, 7 out of 10 classified as italian, the others varying --> xyz.co is not english

**Comment by anshul0708** [comment]
I made a mistake in the above data, the above data is number of English pages and the number non English pages and language not detected pages added up.

Only 1400 pages didn't get their language detected. Feeding a combination of beginning , middle and end of the web pages reduces this to 270 pages. And finally for these small amount of pages we can use franc( which is bit more effective in detecting languages). Only 7-8 pages out of 53500 remained unclassified after this, which were passed as false ( not English ).

**Comment by anshul0708** [comment]
Closed with #56
