### ISSUE TITLE
Create associative array of stemmed tokens with article occurences

### ISSUE THREAD

**Issue by LukasS96** [MusicConnectionMachine/UnstructuredData#55]
After language filtering the result of tokenization and stemming of all articles in a file should result in an array with all the stemmed tokens and their appearances in articles. This will make looking for relevant articles according to the supplied term list very easy. Detailed information about occurences will be looked up later, when the number of remaining articles is much smaller.

The array should have the following structure:
{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"stem1": [article1, article2],
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"stem2": [],
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"stem3": [article3]
}

**Comment by vviro** [comment]
@LukasS96 I would strongly suggest not doing the tokenization on the input. Most of this computation would be wasted and that would be _a lot_ of waste (tokenization is not _that_ fast, right?). If I'm not missing something, you could achieve the same effect by declinating the search terms instead and searching for their different forms. The search would probably take only slightly (if at all) longer, e.g. because stemming takes longer than hashing (btw, regarding matching the keywords (https://github.com/MusicConnectionMachine/UnstructuredData/issues/37) you may want to check out the Bloom filters, they might be one of the best performing data structures for this).

Also, regarding the language detection, this paper is relevant: https://kheafield.com/professional/stanford/crawl_paper.pdf - it seems that the amount of non-english webpages (at least at the point of the paper preparation) was somewhere between 30% and 50%. This means that all the optimizations involving language filtering could bring at most 30-50% in computation time savings. This is really not that much and perhaps at some point it would be more efficient to spend the development effort on some other problem / optimization / feature. I mean, you probably don't have to spend too much time on this language business (https://github.com/MusicConnectionMachine/UnstructuredData/issues/49).

**Comment by vviro** [comment]
> The array should have the following structure: ...
@LukasS96 this is probably a good point to estimate the data size: how large is this matrix going to become? Will it be at all possible to keep it in memory? How many stems and how many articles could we be dealing with here? How much space does an article pointer take? Would multiple processes write into this array? Would they all be running on the same machine?

**Comment by kordianbruck** [comment]
I have to agree with @vviro. We can worry about improving performance further later on. We need to get the pipeline running before we start checking out options that can improve a few percent or sieve out a few more pages.
